#!/bin/sh

# Youtube channel rip
yt-chanrip() { for i in $(curl -s http://gdata.youtube.com/feeds/api/users/"$1"/uploads | grep -Eo "watch\?v=[^[:space:]\"\'\\]{11}" | uniq); do youtube-dl --title --no-overwrites http://youtube.com/"$i"; done }

mk() { mkdir -p "$1"; cd "$1" }

# Google it
google() {
  local term="$@"
  local url="http://www.google.com/search?q=${term// /+}"
  $BROWSER "$url"
}

# https://coderwall.com/p/r2g2rq
todo() {
  git commit --allow-empty -m "TODO: $*"
}

# http://zalas.eu/viewing-svn-diff-result-in-colors/
svndiff() {
  svn diff "${@}" | colordiff
}
